/**
 * Email Bots System - Storage Layer (Supabase Implementation)
 * 
 * Data persistence for bots, logs, and stats using Supabase.
 * Replaces previous file-based storage.
 */

import { createAdminClient } from '../supabase/admin';
import type {
    EmailBot,
    BotExecutionLog,
    BotStats,
    MonitoredThread,
} from './types';

// ============================================================================
// Bot CRUD Operations
// ============================================================================

/**
 * Get all bots for a user
 */
export async function getAllBots(userId: string): Promise<EmailBot[]> {
    const supabase = createAdminClient();

    // We select * because our schema should now match the types (mostly)
    // We might need to map snake_case DB columns to camelCase TS properties if we didn't alias them in SQL 
    // OR Supabase client handles it, but usually it returns what is in DB.
    // Our migration added columns like 'is_premium', 'accepted_terms_at'. 
    // We need to map these manually or use a helper.

    const { data, error } = await supabase
        .from('bots')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Error fetching bots:', error);
        throw new Error('Failed to fetch bots');
    }

    return (data || []).map(row => mapRowToBot(row));
}

/**
 * Get bot by ID
 */
export async function getBotById(
    botId: string,
    userId: string
): Promise<EmailBot | null> {
    const supabase = createAdminClient();

    const { data, error } = await supabase
        .from('bots')
        .select('*')
        .eq('id', botId)
        .eq('user_id', userId)
        .single();

    if (error) {
        if (error.code === 'PGRST116') return null; // No rows found
        console.error('Error fetching bot:', error);
        throw new Error('Failed to fetch bot');
    }

    return mapRowToBot(data);
}

/**
 * Get enabled bots for a user
 */
export async function getEnabledBots(userId: string): Promise<EmailBot[]> {
    const supabase = createAdminClient();

    const { data, error } = await supabase
        .from('bots')
        .select('*')
        .eq('user_id', userId)
        .eq('enabled', true);

    if (error) return [];

    return (data || []).map(row => mapRowToBot(row));
}

/**
 * Create a new bot
 */
export async function createBot(bot: EmailBot): Promise<EmailBot> {
    const supabase = createAdminClient();

    const dbRow = mapBotToRow(bot);
    // Remove ID if it's auto-generated by DB? 
    // But our ID is uuid, so we can pass it if we generated it in code.
    // The previous implementation generated ID in action. Let's keep that.

    const { data, error } = await supabase
        .from('bots')
        .insert(dbRow)
        .select()
        .single();

    if (error) {
        console.error('Error creating bot:', error);
        throw new Error('Failed to create bot');
    }

    return mapRowToBot(data);
}

/**
 * Update a bot
 */
export async function updateBot(
    botId: string,
    userId: string,
    updates: Partial<EmailBot>
): Promise<EmailBot> {
    const supabase = createAdminClient();

    // Map updates to DB columns
    const dbUpdates: any = {};
    if (updates.name) dbUpdates.name = updates.name;
    if (updates.description) dbUpdates.description = updates.description;
    if (updates.enabled !== undefined) dbUpdates.enabled = updates.enabled;
    if (updates.isPremium !== undefined) dbUpdates.is_premium = updates.isPremium;
    if (updates.trigger) dbUpdates.trigger = updates.trigger;
    if (updates.conditions) dbUpdates.conditions = updates.conditions;
    if (updates.actions) dbUpdates.actions = updates.actions;
    if (updates.safety) dbUpdates.safety = updates.safety;
    if (updates.stats) dbUpdates.stats = updates.stats;
    if (updates.acceptedTermsAt) dbUpdates.accepted_terms_at = updates.acceptedTermsAt;
    if (updates.acceptedTermsVersion) dbUpdates.accepted_terms_version = updates.acceptedTermsVersion;

    dbUpdates.updated_at = new Date().toISOString();

    const { data, error } = await supabase
        .from('bots')
        .update(dbUpdates)
        .eq('id', botId)
        .eq('user_id', userId)
        .select()
        .single();

    if (error) {
        console.error('Error updating bot:', error);
        throw new Error('Failed to update bot');
    }

    return mapRowToBot(data);
}

/**
 * Delete a bot
 */
export async function deleteBot(botId: string, userId: string): Promise<void> {
    const supabase = createAdminClient();

    const { error } = await supabase
        .from('bots')
        .delete()
        .eq('id', botId)
        .eq('user_id', userId);

    if (error) {
        console.error('Error deleting bot:', error);
        throw new Error('Failed to delete bot');
    }
}

// ============================================================================
// Execution Logs
// ============================================================================

/**
 * Log a bot execution
 */
export async function logExecution(log: BotExecutionLog): Promise<void> {
    const supabase = createAdminClient();

    const { error } = await supabase
        .from('bot_execution_logs')
        .insert({
            bot_id: log.botId,
            email_id: log.emailId,
            triggered_at: log.triggeredAt,
            status: log.status,
            actions_executed: log.actionsExecuted,
            error_message: log.errorMessage,
            metadata: log.metadata
        });

    if (error) {
        console.error('Error logging execution:', error);
        // Don't throw, just log error so we don't break flow
    }
}

/**
 * Get execution logs for a bot
 */
export async function getExecutionLogs(
    botId: string,
    limit = 100
): Promise<BotExecutionLog[]> {
    const supabase = createAdminClient();

    const { data, error } = await supabase
        .from('bot_execution_logs')
        .select('*')
        .eq('bot_id', botId)
        .order('triggered_at', { ascending: false })
        .limit(limit);

    if (error) {
        console.error('Error fetching logs:', error);
        return [];
    }

    return (data || []).map(row => ({
        id: row.id,
        botId: row.bot_id,
        emailId: row.email_id,
        triggeredAt: new Date(row.triggered_at),
        status: row.status as any,
        actionsExecuted: row.actions_executed || [],
        errorMessage: row.error_message,
        metadata: row.metadata
    }));
}

/**
 * Count successful sends today for a bot
 */
export async function countSendsToday(botId: string): Promise<number> {
    // Implementation would need a date filter query
    // For now, simpler to fetch recent logs or trust the Stats field
    const supabase = createAdminClient();
    const today = new Date().toISOString().split('T')[0];

    const { count, error } = await supabase
        .from('bot_execution_logs')
        .select('*', { count: 'exact', head: true })
        .eq('bot_id', botId)
        .eq('status', 'success')
        .gte('triggered_at', `${today}T00:00:00.000Z`);

    if (error) return 0;
    return count || 0;
}

/**
 * Get last send time to a specific email for a bot
 */
export async function getLastSentTo(
    botId: string,
    email: string
): Promise<Date | null> {
    const supabase = createAdminClient();

    // This is tricky because senderEmail is in metadata jsonb
    // Supabase allows filtering on jsonb columns
    const { data, error } = await supabase
        .from('bot_execution_logs')
        .select('triggered_at')
        .eq('bot_id', botId)
        .eq('status', 'success')
        .contains('metadata', { senderEmail: email })
        .order('triggered_at', { ascending: false })
        .limit(1)
        .single();

    if (error || !data) return null;

    return new Date(data.triggered_at);
}

// ============================================================================
// Bot Stats
// ============================================================================

/**
 * Get bot statistics
 * (For Supabase, simpler to just read it from the bot record itself, checking `stats` column)
 */
export async function getBotStats(botId: string): Promise<BotStats | null> {
    // We can just fetch the bot and return its stats
    // The previous implementation had a separate file. 
    // In our DB schema, we put 'stats' as a JSONB column on the 'bots' table.
    // However, if we want to run atomic updates (increments), we might need an RPC or separate table.
    // For now, let's just query the bot.

    const supabase = createAdminClient();
    const { data, error } = await supabase
        .from('bots')
        .select('stats, updated_at') // we might want updated_at as lastExecuted? No, stats has it.
        .eq('id', botId)
        .single();

    if (error || !data) return null;

    // Ensure stats object has defaults
    const stats = data.stats || {};
    return {
        totalExecutions: stats.totalExecutions || 0,
        lastExecutedAt: stats.lastExecutedAt ? new Date(stats.lastExecutedAt) : undefined,
        successCount: stats.successCount || 0,
        failureCount: stats.failureCount || 0,
        emailsSent: stats.emailsSent || 0,
        draftsCreated: stats.draftsCreated || 0,
        lastUsedTemplate: stats.lastUsedTemplate,
    };
}

/**
 * Update bot stats incrementally
 */
export async function updateBotStats(
    botId: string,
    result: {
        success: boolean;
        emailsSent?: number;
        draftsCreated?: number;
        lastUsedTemplate?: string;
    }
): Promise<void> {
    const currentStats = await getBotStats(botId) || {
        totalExecutions: 0,
        successCount: 0,
        failureCount: 0,
        emailsSent: 0,
        draftsCreated: 0,
    };

    const newStats: BotStats = {
        ...currentStats,
        totalExecutions: (currentStats.totalExecutions || 0) + 1,
        lastExecutedAt: new Date(),
        successCount: (currentStats.successCount || 0) + (result.success ? 1 : 0),
        failureCount: (currentStats.failureCount || 0) + (result.success ? 0 : 1),
        emailsSent: (currentStats.emailsSent || 0) + (result.emailsSent || 0),
        draftsCreated: (currentStats.draftsCreated || 0) + (result.draftsCreated || 0),
        lastUsedTemplate: result.lastUsedTemplate || currentStats.lastUsedTemplate,
    };

    await saveBotStats(botId, newStats);
}

/**
 * Save bot statistics
 */
export async function saveBotStats(botId: string, stats: BotStats): Promise<void> {
    const supabase = createAdminClient();

    await supabase
        .from('bots')
        .update({ stats: stats as any })
        .eq('id', botId);
}

// Helpers

function mapRowToBot(row: any): EmailBot {
    return {
        id: row.id,
        userId: row.user_id,
        name: row.name,
        description: row.description,
        prompt: row.prompt,
        enabled: row.enabled ?? true, // Default to true if null/missing
        isPremium: row.is_premium ?? false,
        createdAt: new Date(row.created_at),
        updatedAt: new Date(row.updated_at),
        trigger: row.trigger || {},
        conditions: row.conditions || [],
        actions: row.actions || [],
        safety: row.safety || {},
        stats: row.stats || {
            totalExecutions: 0,
            successCount: 0,
            failureCount: 0,
            emailsSent: 0,
            draftsCreated: 0,
            lastUsedTemplate: undefined
        },
        acceptedTermsAt: row.accepted_terms_at ? new Date(row.accepted_terms_at) : undefined,
        acceptedTermsVersion: row.accepted_terms_version
    };
}

function mapBotToRow(bot: EmailBot): any {
    return {
        id: bot.id,
        user_id: bot.userId,
        name: bot.name,
        description: bot.description,
        prompt: bot.prompt || '',
        enabled: bot.enabled,
        is_premium: bot.isPremium,
        created_at: bot.createdAt,
        updated_at: bot.updatedAt,
        trigger: bot.trigger,
        conditions: bot.conditions,
        actions: bot.actions,
        safety: bot.safety,
        stats: bot.stats,
        accepted_terms_at: bot.acceptedTermsAt,
        accepted_terms_version: bot.acceptedTermsVersion
    };
}

// ============================================================================
// Monitored Threads (Follow-Ups)
// ============================================================================

/**
 * Get monitored threads for a bot
 */
export async function getMonitoredThreads(botId: string): Promise<MonitoredThread[]> {
    const supabase = createAdminClient();

    const { data, error } = await supabase
        .from('monitored_threads')
        .select('*')
        .eq('bot_id', botId)
        .order('added_at', { ascending: false });

    if (error) {
        console.error('Error fetching monitored threads:', error);
        return [];
    }

    return (data || []).map(row => ({
        id: row.id,
        bot_id: row.bot_id,
        thread_id: row.thread_id,
        subject: row.subject,
        recipient: row.recipient,
        added_at: row.added_at, // Alread ISO string from DB? Or Date? DB returns string usually.
        scheduled_for: row.scheduled_for,
        status: row.status as any,
        attempts: row.attempts || 0,
        last_error: row.last_error
    }));
}

/**
 * Get a specific monitored thread by ID
 */
export async function getMonitoredThreadById(id: string): Promise<MonitoredThread | null> {
    const supabase = createAdminClient();

    const { data, error } = await supabase
        .from('monitored_threads')
        .select('*')
        .eq('id', id)
        .single();

    if (error) {
        if (error.code === 'PGRST116') return null; // No rows found
        console.error('Error fetching monitored thread:', error);
        throw new Error('Failed to fetch monitored thread');
    }

    return {
        id: data.id,
        bot_id: data.bot_id,
        thread_id: data.thread_id,
        subject: data.subject,
        recipient: data.recipient,
        added_at: data.added_at,
        scheduled_for: data.scheduled_for,
        status: data.status as any,
        attempts: data.attempts || 0,
        last_error: data.last_error
    };
}

/**
 * Add a thread to monitoring
 */
export async function addMonitoredThread(thread: Partial<MonitoredThread> & { bot_id: string; thread_id: string }): Promise<MonitoredThread | null> {
    const supabase = createAdminClient();

    const dbRow = {
        bot_id: thread.bot_id,
        thread_id: thread.thread_id,
        subject: thread.subject || 'No Subject',
        recipient: thread.recipient || 'Unknown',
        added_at: thread.added_at ? thread.added_at : new Date().toISOString(),
        scheduled_for: thread.scheduled_for ? thread.scheduled_for : new Date().toISOString(),
        status: thread.status || 'pending',
        attempts: thread.attempts || 0
    };

    const { data, error } = await supabase
        .from('monitored_threads')
        .insert(dbRow)
        .select()
        .single();

    if (error) {
        console.error('Error adding monitored thread:', error);
        return null; // Or throw
    }

    return {
        id: data.id,
        bot_id: data.bot_id,
        thread_id: data.thread_id,
        subject: data.subject,
        recipient: data.recipient,
        added_at: data.added_at,
        scheduled_for: data.scheduled_for,
        status: data.status as any,
        attempts: data.attempts,
        last_error: data.last_error
    };
}

/**
 * Update a monitored thread
 */
export async function updateMonitoredThread(id: string, updates: Partial<MonitoredThread>): Promise<void> {
    const supabase = createAdminClient();

    const dbUpdates: any = {};
    if (updates.status) dbUpdates.status = updates.status;
    if (updates.attempts !== undefined) dbUpdates.attempts = updates.attempts;
    if (updates.last_error) dbUpdates.last_error = updates.last_error;

    const { error } = await supabase
        .from('monitored_threads')
        .update(dbUpdates)
        .eq('id', id);

    if (error) {
        console.error('Error updating monitored thread:', error);
        throw new Error('Failed to update monitored thread');
    }
}

/**
 * Delete a monitored thread
 */
export async function deleteMonitoredThread(id: string): Promise<void> {
    const supabase = createAdminClient();

    const { error } = await supabase
        .from('monitored_threads')
        .delete()
        .eq('id', id);

    if (error) {
        console.error('Error deleting monitored thread:', error);
        throw new Error('Failed to delete monitored thread');
    }
}
